// ── 사용설명서(ManualModal) 번역 테이블 ─────────────────────────
// 분량이 커서 strings.js에서 분리. 구조는 동일: { key: { ko, en, ja, zh, es, fr, de, pt, ru, it } }
// index.js에서 STRINGS와 합쳐 t()가 조회한다. 키 이름은 m으로 시작.
export const MANUAL_STRINGS = {
  // ── 공통 ──
  mHeaderMeta: { ko: '사용설명서 {cur} / {total}', en: 'Guide {cur} / {total}', ja: '使い方 {cur} / {total}', zh: '使用说明 {cur} / {total}', es: 'Guía {cur} / {total}', fr: 'Guide {cur} / {total}', de: 'Anleitung {cur} / {total}', pt: 'Guia {cur} / {total}', ru: 'Руководство {cur} / {total}', it: 'Guida {cur} / {total}' },
  mPrev:  { ko: '← 이전', en: '← Back', ja: '← 前へ', zh: '← 上一页', es: '← Atrás', fr: '← Précédent', de: '← Zurück', pt: '← Voltar', ru: '← Назад', it: '← Indietro' },
  mNext:  { ko: '다음 →', en: 'Next →', ja: '次へ →', zh: '下一页 →', es: 'Siguiente →', fr: 'Suivant →', de: 'Weiter →', pt: 'Próximo →', ru: 'Далее →', it: 'Avanti →' },
  mClose: { ko: '닫기 ✓', en: 'Done ✓', ja: '閉じる ✓', zh: '关闭 ✓', es: 'Listo ✓', fr: 'Terminé ✓', de: 'Fertig ✓', pt: 'Concluir ✓', ru: 'Готово ✓', it: 'Fatto ✓' },
  mPerMonth: { ko: '/ 월', en: '/ month', ja: '/ 月', zh: '/ 月', es: '/ mes', fr: '/ mois', de: '/ Monat', pt: '/ mês', ru: '/ мес.', it: '/ mese' },

  // ── 페이지 제목 ──
  mTitle1: { ko: '시작 전에', en: 'Before you start', ja: 'はじめる前に', zh: '开始之前', es: 'Antes de empezar', fr: 'Avant de commencer', de: 'Bevor du startest', pt: 'Antes de começar', ru: 'Перед началом', it: 'Prima di iniziare' },
  mTitle2: { ko: '코드 탭', en: 'Chords tab', ja: 'コードタブ', zh: '和弦标签页', es: 'Pestaña Acordes', fr: 'Onglet Accords', de: 'Tab „Akkorde“', pt: 'Aba Acordes', ru: 'Вкладка «Аккорды»', it: 'Scheda Accordi' },
  mTitle3: { ko: '운지 다이어그램', en: 'Fingering diagrams', ja: '運指ダイアグラム', zh: '指法图', es: 'Diagramas de digitación', fr: 'Diagrammes de doigté', de: 'Griffdiagramme', pt: 'Diagramas de digitação', ru: 'Схемы аппликатур', it: 'Diagrammi di diteggiatura' },
  mTitle4: { ko: '전조 & 저장', en: 'Transpose & save', ja: '移調と保存', zh: '移调与保存', es: 'Transportar y guardar', fr: 'Transposer et enregistrer', de: 'Transponieren & Speichern', pt: 'Transpor e salvar', ru: 'Транспозиция и сохранение', it: 'Trasporre e salvare' },
  mTitle5: { ko: '스케일 탭', en: 'Scales tab', ja: 'スケールタブ', zh: '音阶标签页', es: 'Pestaña Escalas', fr: 'Onglet Gammes', de: 'Tab „Skalen“', pt: 'Aba Escalas', ru: 'Вкладка «Гаммы»', it: 'Scheda Scale' },
  mTitle6: { ko: '분석 탭 (AI)', en: 'Analyze tab (AI)', ja: '分析タブ（AI）', zh: '分析标签页（AI）', es: 'Pestaña Análisis (IA)', fr: 'Onglet Analyse (IA)', de: 'Tab „Analyse“ (KI)', pt: 'Aba Análise (IA)', ru: 'Вкладка «Анализ» (ИИ)', it: 'Scheda Analisi (IA)' },
  mTitle7: { ko: '실전 활용', en: 'Putting it to work', ja: '実践での使い方', zh: '实战用法', es: 'Ponerlo en práctica', fr: 'Mise en pratique', de: 'In der Praxis', pt: 'Na prática', ru: 'На практике', it: 'Metterlo in pratica' },
  mTitle8: { ko: '프리미엄', en: 'Premium', ja: 'プレミアム', zh: '高级版', es: 'Premium', fr: 'Premium', de: 'Premium', pt: 'Premium', ru: 'Премиум', it: 'Premium' },

  // ── 1. 시작 전에 ──
  mIntro: { ko: 'ChordNavigator는 코드 진행을 탐색하고, 소리를 들어보고, 운지를 확인하고, AI로 분석까지 할 수 있는 도구예요.', en: 'ChordNavigator is a tool for exploring chord progressions, hearing them, checking fingerings, and analyzing them with AI.', ja: 'ChordNavigatorは、コード進行を探して、音を聴いて、運指を確認し、AIで分析までできるツールです。', zh: 'ChordNavigator 是一个能探索和弦进行、试听声音、查看指法，还能用 AI 分析的工具。', es: 'ChordNavigator es una herramienta para explorar progresiones de acordes, escucharlas, ver digitaciones y analizarlas con IA.', fr: 'ChordNavigator est un outil pour explorer des progressions d’accords, les écouter, voir les doigtés et les analyser avec l’IA.', de: 'ChordNavigator ist ein Werkzeug, um Akkordfolgen zu erkunden, zu hören, Griffe zu prüfen und mit KI zu analysieren.', pt: 'O ChordNavigator é uma ferramenta para explorar progressões de acordes, ouvi-las, ver digitações e analisá-las com IA.', ru: 'ChordNavigator — инструмент, чтобы искать последовательности аккордов, слушать их, смотреть аппликатуры и анализировать с помощью ИИ.', it: 'ChordNavigator è uno strumento per esplorare progressioni di accordi, ascoltarle, vedere le diteggiature e analizzarle con l’IA.' },
  mStep1Label: { ko: '키 선택', en: 'Pick a key', ja: 'キーを選ぶ', zh: '选择调', es: 'Elige la tonalidad', fr: 'Choisir la tonalité', de: 'Tonart wählen', pt: 'Escolha o tom', ru: 'Выберите тональность', it: 'Scegli la tonalità' },
  mStep1Desc: { ko: '홈에서 연주할 키(C, G, Am…)와 장/단조 선택', en: 'On the home screen, choose the key (C, G, Am…) and major or minor', ja: 'ホームで演奏するキー（C, G, Am…）と長調・短調を選択', zh: '在首页选择要演奏的调（C、G、Am…）与大调/小调', es: 'En la pantalla de inicio, elige la tonalidad (C, G, Am…) y mayor o menor', fr: 'Sur l’écran d’accueil, choisissez la tonalité (C, G, Am…) et majeur ou mineur', de: 'Wähle auf dem Startbildschirm Tonart (C, G, Am…) und Dur oder Moll', pt: 'Na tela inicial, escolha o tom (C, G, Am…) e maior ou menor', ru: 'На главном экране выберите тональность (C, G, Am…) и мажор или минор', it: 'Nella schermata iniziale scegli la tonalità (C, G, Am…) e maggiore o minore' },
  mStep2Label: { ko: '탐색 시작', en: 'Start exploring', ja: '探索を開始', zh: '开始探索', es: 'Empieza a explorar', fr: 'Lancer l’exploration', de: 'Erkundung starten', pt: 'Comece a explorar', ru: 'Начните поиск', it: 'Inizia a esplorare' },
  mStep2Desc: { ko: '▶ 버튼으로 Navigator 진입', en: 'Tap ▶ to enter the Navigator', ja: '▶ ボタンでNavigatorに入る', zh: '点 ▶ 进入 Navigator', es: 'Pulsa ▶ para entrar en el Navigator', fr: 'Appuyez sur ▶ pour ouvrir le Navigator', de: 'Mit ▶ in den Navigator gehen', pt: 'Toque em ▶ para entrar no Navigator', ru: 'Нажмите ▶, чтобы войти в Navigator', it: 'Tocca ▶ per entrare nel Navigator' },
  mStep3Label: { ko: '코드 탭', en: 'Tap chords', ja: 'コードをタップ', zh: '点击和弦', es: 'Toca acordes', fr: 'Toucher les accords', de: 'Akkorde antippen', pt: 'Toque nos acordes', ru: 'Нажимайте аккорды', it: 'Tocca gli accordi' },
  mStep3Desc: { ko: '코드 카드를 탭 → 소리 재생 + 진행에 추가', en: 'Tap a chord card → it plays and joins your progression', ja: 'コードカードをタップ → 音が鳴り進行に追加', zh: '点击和弦卡片 → 发声并加入进行', es: 'Toca una tarjeta de acorde: suena y se añade a tu progresión', fr: 'Touchez une carte d’accord : il sonne et rejoint votre progression', de: 'Akkordkarte antippen → er klingt und landet in deiner Folge', pt: 'Toque em um card de acorde: ele soa e entra na sua progressão', ru: 'Нажмите карточку аккорда — он прозвучит и попадёт в последовательность', it: 'Tocca una carta accordo: suona e si aggiunge alla progressione' },
  mStep4Label: { ko: '진행 저장', en: 'Save it', ja: '進行を保存', zh: '保存进行', es: 'Guárdala', fr: 'Enregistrer', de: 'Speichern', pt: 'Salve', ru: 'Сохраните', it: 'Salvala' },
  mStep4Desc: { ko: '☆ 버튼으로 이름 붙여 저장, 언제든 불러오기', en: 'Use ☆ to save with a name and load it back any time', ja: '☆ ボタンで名前を付けて保存、いつでも読み込み', zh: '用 ☆ 命名保存，随时载入', es: 'Usa ☆ para guardar con un nombre y cargarla cuando quieras', fr: 'Utilisez ☆ pour enregistrer avec un nom et la recharger quand vous voulez', de: 'Mit ☆ unter einem Namen speichern und jederzeit laden', pt: 'Use ☆ para salvar com um nome e carregar quando quiser', ru: 'Кнопкой ☆ сохраните с именем и загрузите в любой момент', it: 'Usa ☆ per salvarla con un nome e ricaricarla quando vuoi' },
  mStep5Label: { ko: '분석·스케일', en: 'Analyze & scales', ja: '分析・スケール', zh: '分析·音阶', es: 'Análisis y escalas', fr: 'Analyse et gammes', de: 'Analyse & Skalen', pt: 'Análise e escalas', ru: 'Анализ и гаммы', it: 'Analisi e scale' },
  mStep5Desc: { ko: '하단 탭으로 이동해 AI 분석 또는 스케일 탐색', en: 'Switch tabs at the bottom for AI analysis or scale exploring', ja: '下部タブに移動してAI分析やスケール探索', zh: '切到底部标签，做 AI 分析或探索音阶', es: 'Cambia de pestaña abajo para el análisis con IA o explorar escalas', fr: 'Changez d’onglet en bas pour l’analyse IA ou l’exploration des gammes', de: 'Unten den Tab wechseln für KI-Analyse oder Skalensuche', pt: 'Troque de aba embaixo para análise com IA ou explorar escalas', ru: 'Переключите нижнюю вкладку для ИИ-анализа или поиска гамм', it: 'Cambia scheda in basso per l’analisi IA o per esplorare le scale' },

  // ── 2. 코드 탭 ──
  m2s1Label: { ko: '코드 카드 한 번 탭', en: 'Single tap on a chord card', ja: 'コードカードを1回タップ', zh: '轻点和弦卡片一次', es: 'Un toque en la tarjeta de acorde', fr: 'Un appui sur une carte d’accord', de: 'Einmal auf eine Akkordkarte tippen', pt: 'Um toque no card do acorde', ru: 'Одно нажатие на карточку аккорда', it: 'Un tocco sulla carta accordo' },
  m2s1Desc: { ko: '소리 재생 + 하단 진행 바에 추가. 길게 누르면 삭제.', en: 'Plays the chord and adds it to the progression bar. Long-press to remove.', ja: '音が鳴り、下の進行バーに追加。長押しで削除。', zh: '发声并加入下方进行栏。长按可删除。', es: 'Suena y se añade a la barra de progresión. Mantén pulsado para borrar.', fr: 'L’accord sonne et s’ajoute à la barre de progression. Appui long pour supprimer.', de: 'Der Akkord erklingt und kommt in die Folgenleiste. Langes Drücken löscht ihn.', pt: 'Toca o acorde e o adiciona à barra de progressão. Pressione e segure para remover.', ru: 'Аккорд звучит и добавляется в панель последовательности. Долгое нажатие удаляет.', it: 'Suona e si aggiunge alla barra della progressione. Tieni premuto per eliminarlo.' },
  m2s2Label: { ko: '변형 버튼 (maj7, sus4…)', en: 'Variant buttons (maj7, sus4…)', ja: '変形ボタン（maj7, sus4…）', zh: '变体按钮（maj7、sus4…）', es: 'Botones de variante (maj7, sus4…)', fr: 'Boutons de variante (maj7, sus4…)', de: 'Varianten-Buttons (maj7, sus4…)', pt: 'Botões de variante (maj7, sus4…)', ru: 'Кнопки вариантов (maj7, sus4…)', it: 'Pulsanti varianti (maj7, sus4…)' },
  m2s2Desc: { ko: '선택된 코드 아래에 표시. 탭하면 해당 변형음으로 교체.', en: 'They appear under the selected chord. Tap one to swap in that variant.', ja: '選択したコードの下に表示。タップするとその変形に置き換わります。', zh: '显示在所选和弦下方。点一下就换成该变体。', es: 'Aparecen bajo el acorde elegido. Tócalos para cambiar a esa variante.', fr: 'Ils apparaissent sous l’accord sélectionné. Touchez pour passer à cette variante.', de: 'Sie erscheinen unter dem gewählten Akkord. Antippen tauscht die Variante ein.', pt: 'Aparecem sob o acorde selecionado. Toque para trocar por aquela variante.', ru: 'Появляются под выбранным аккордом. Нажатие подставляет этот вариант.', it: 'Compaiono sotto l’accordo scelto. Toccane uno per sostituirlo con quella variante.' },
  m2s3Label: { ko: '▶ 재생 버튼', en: '▶ Play button', ja: '▶ 再生ボタン', zh: '▶ 播放按钮', es: 'Botón ▶ de reproducción', fr: 'Bouton ▶ Lecture', de: '▶ Wiedergabe-Taste', pt: 'Botão ▶ de reprodução', ru: 'Кнопка ▶', it: 'Pulsante ▶ di riproduzione' },
  m2s3Desc: { ko: '진행 바의 코드를 순서대로 재생. 템포(BPM)는 옆에서 조절.', en: 'Plays the progression in order. Set the tempo (BPM) right next to it.', ja: '進行バーのコードを順番に再生。テンポ（BPM）は隣で調整。', zh: '按顺序播放进行栏的和弦。速度（BPM）在旁边调整。', es: 'Reproduce la progresión en orden. El tempo (BPM) se ajusta al lado.', fr: 'Joue la progression dans l’ordre. Le tempo (BPM) se règle juste à côté.', de: 'Spielt die Folge der Reihe nach. Das Tempo (BPM) stellst du daneben ein.', pt: 'Toca a progressão em ordem. O andamento (BPM) se ajusta ao lado.', ru: 'Проигрывает последовательность по порядку. Темп (BPM) задаётся рядом.', it: 'Riproduce la progressione in ordine. Il tempo (BPM) si regola accanto.' },
  m2s4Label: { ko: 'GPS 루트', en: 'GPS routes', ja: 'GPSルート', zh: 'GPS 路线', es: 'Rutas GPS', fr: 'Itinéraires GPS', de: 'GPS-Routen', pt: 'Rotas GPS', ru: 'GPS-маршруты', it: 'Percorsi GPS' },
  m2s4Desc: { ko: '현재 진행 맥락을 분석해 다음 코드를 자동 추천. AI(프리미엄) 또는 규칙 기반으로 작동.', en: 'Reads the context of your progression and suggests where to go next — by AI (Premium) or by rules.', ja: '今の進行の流れを読んで次のコードを自動提案。AI（プレミアム）またはルールベースで動作。', zh: '分析当前进行的走向，自动推荐下一个和弦。可用 AI（高级版）或规则运作。', es: 'Lee el contexto de tu progresión y sugiere el siguiente acorde, con IA (Premium) o por reglas.', fr: 'Analyse le contexte de votre progression et propose la suite — par IA (Premium) ou par règles.', de: 'Liest den Kontext deiner Folge und schlägt den nächsten Akkord vor — per KI (Premium) oder Regeln.', pt: 'Lê o contexto da sua progressão e sugere o próximo acorde, por IA (Premium) ou por regras.', ru: 'Учитывает контекст последовательности и подсказывает следующий аккорд — через ИИ (Премиум) или по правилам.', it: 'Legge il contesto della progressione e propone l’accordo successivo, con IA (Premium) o a regole.' },
  m2s5Label: { ko: '마디 (▐)', en: 'Bars (▐)', ja: '小節（▐）', zh: '小节（▐）', es: 'Compases (▐)', fr: 'Mesures (▐)', de: 'Takte (▐)', pt: 'Compassos (▐)', ru: 'Такты (▐)', it: 'Battute (▐)' },
  m2s5Desc: { ko: '진행을 마디 단위로 구분. [마디] 버튼을 눌러 코드 사이의 마디줄을 옮길 수 있어요.', en: 'Splits the progression into bars. Tap [Bars] to move the bar lines between chords.', ja: '進行を小節単位で区切ります。[小節]ボタンでコード間の小節線を動かせます。', zh: '把进行按小节划分。点 [小节] 可移动和弦之间的小节线。', es: 'Divide la progresión en compases. Pulsa [Compases] para mover las barras entre acordes.', fr: 'Découpe la progression en mesures. Touchez [Mesures] pour déplacer les barres entre les accords.', de: 'Teilt die Folge in Takte. Über [Takte] verschiebst du die Taktstriche zwischen Akkorden.', pt: 'Divide a progressão em compassos. Toque em [Compassos] para mover as barras entre acordes.', ru: 'Делит последовательность на такты. Нажмите [Такты], чтобы двигать тактовые черты между аккордами.', it: 'Divide la progressione in battute. Tocca [Battute] per spostare le stanghette tra gli accordi.' },
  m2Tip: { ko: '진행 바로 아래에 기타·피아노 운지 다이어그램이 함께 나와요. 재생 중에는 연주되는 코드를 따라갑니다.', en: 'Guitar and piano fingering diagrams sit right under the progression — during playback they follow the chord being played.', ja: '進行のすぐ下にギター・ピアノの運指図が出ます。再生中は鳴っているコードに追従します。', zh: '进行下方就有吉他与钢琴指法图，播放时会跟着当前和弦走。', es: 'Justo debajo de la progresión están los diagramas de guitarra y piano; durante la reproducción siguen al acorde que suena.', fr: 'Les diagrammes guitare et piano sont juste sous la progression et suivent l’accord joué pendant la lecture.', de: 'Direkt unter der Folge stehen die Griffdiagramme für Gitarre und Klavier — bei der Wiedergabe folgen sie dem klingenden Akkord.', pt: 'Logo abaixo da progressão ficam os diagramas de violão e piano; na reprodução eles seguem o acorde tocado.', ru: 'Прямо под последовательностью — схемы для гитары и пианино; при воспроизведении они следуют за звучащим аккордом.', it: 'Sotto la progressione ci sono i diagrammi per chitarra e piano: durante la riproduzione seguono l’accordo suonato.' },

  // ── 3. 운지 다이어그램 ──
  m3s1Label: { ko: '기타 다이어그램', en: 'Guitar diagram', ja: 'ギターダイアグラム', zh: '吉他指法图', es: 'Diagrama de guitarra', fr: 'Diagramme de guitare', de: 'Gitarrendiagramm', pt: 'Diagrama de violão', ru: 'Схема для гитары', it: 'Diagramma per chitarra' },
  m3s1Desc: { ko: '프렛 번호 + 손가락 위치를 점으로 표시. X는 뮤트, O는 개방현.', en: 'Fret numbers with dots for finger positions. X means muted, O means open string.', ja: 'フレット番号と指の位置を点で表示。Xはミュート、Oは開放弦。', zh: '用点标出品位与手指位置。X 表示闷音，O 表示空弦。', es: 'Números de traste con puntos para los dedos. X es cuerda muda; O, cuerda al aire.', fr: 'Numéros de case et points pour les doigts. X = corde étouffée, O = corde à vide.', de: 'Bundnummern mit Punkten für die Finger. X heißt gedämpft, O heißt leere Saite.', pt: 'Números de casa com pontos para os dedos. X é abafada; O, corda solta.', ru: 'Номера ладов и точки для пальцев. X — заглушенная струна, O — открытая.', it: 'Numeri di tasto con punti per le dita. X = corda smorzata, O = corda a vuoto.' },
  m3s2Label: { ko: '피아노 다이어그램', en: 'Piano diagram', ja: 'ピアノダイアグラム', zh: '钢琴键位图', es: 'Diagrama de piano', fr: 'Diagramme de piano', de: 'Klavierdiagramm', pt: 'Diagrama de piano', ru: 'Схема для пианино', it: 'Diagramma per piano' },
  m3s2Desc: { ko: '구성음을 건반 위에 하이라이트. 루트 음은 강조 색으로 표시. 전위(1·2전위)도 볼 수 있어요.', en: 'Highlights the chord tones on the keys, with the root in an accent color. Inversions (1st, 2nd) are available too.', ja: '構成音を鍵盤上にハイライト。ルート音は強調色。転回形（第1・第2）も見られます。', zh: '在键盘上高亮组成音，根音用强调色。也能查看第一、第二转位。', es: 'Resalta las notas del acorde en las teclas, con la fundamental en color de acento. También hay inversiones (1.ª y 2.ª).', fr: 'Met en évidence les notes de l’accord sur les touches, la fondamentale en couleur d’accent. Les renversements (1er, 2e) sont aussi disponibles.', de: 'Hebt die Akkordtöne auf den Tasten hervor, den Grundton in Akzentfarbe. Umkehrungen (1./2.) gibt es auch.', pt: 'Destaca as notas do acorde nas teclas, com a fundamental em cor de destaque. Também há inversões (1.ª e 2.ª).', ru: 'Подсвечивает тоны аккорда на клавишах, основной тон — акцентным цветом. Есть и обращения (1-е, 2-е).', it: 'Evidenzia le note dell’accordo sui tasti, con la fondamentale in colore d’accento. Ci sono anche i rivolti (1º, 2º).' },
  m3s3Label: { ko: '기타 지판 (스케일 탭)', en: 'Guitar fretboard (Scales tab)', ja: 'ギター指板（スケールタブ）', zh: '吉他指板（音阶标签页）', es: 'Diapasón de guitarra (pestaña Escalas)', fr: 'Manche de guitare (onglet Gammes)', de: 'Gitarrengriffbrett (Tab „Skalen“)', pt: 'Braço do violão (aba Escalas)', ru: 'Гриф гитары (вкладка «Гаммы»)', it: 'Manico della chitarra (scheda Scale)' },
  m3s3Desc: { ko: '선택한 스케일의 모든 음 위치를 전체 지판에 시각화.', en: 'Shows every note of the selected scale across the whole fretboard.', ja: '選んだスケールの全ての音の位置を指板全体に可視化。', zh: '把所选音阶的所有音位置显示在整个指板上。', es: 'Muestra todas las notas de la escala elegida en todo el diapasón.', fr: 'Affiche toutes les notes de la gamme choisie sur tout le manche.', de: 'Zeigt alle Töne der gewählten Skala auf dem ganzen Griffbrett.', pt: 'Mostra todas as notas da escala escolhida em todo o braço.', ru: 'Показывает все ноты выбранной гаммы по всему грифу.', it: 'Mostra tutte le note della scala scelta su tutto il manico.' },
  m3Tip: { ko: '운지 데이터 없음이 뜨면 해당 코드 변형이 아직 등록되지 않은 거예요. 기본 코드(maj/min)는 항상 표시됩니다.', en: 'If it says there is no fingering data, that chord variant is not in the library yet. Basic chords (maj/min) always show.', ja: '「運指データなし」と出たら、そのコード変形がまだ登録されていません。基本コード（maj/min）は常に表示されます。', zh: '如果显示没有指法数据，说明该变体尚未收录。基本和弦（maj/min）始终会显示。', es: 'Si dice que no hay datos de digitación, esa variante aún no está en la biblioteca. Los acordes básicos (maj/min) siempre aparecen.', fr: 'Si « pas de doigté » s’affiche, cette variante n’est pas encore répertoriée. Les accords de base (maj/min) sont toujours affichés.', de: 'Steht dort „keine Griffdaten“, fehlt diese Variante noch. Grundakkorde (Dur/Moll) werden immer angezeigt.', pt: 'Se aparecer que não há dados de digitação, essa variante ainda não está cadastrada. Acordes básicos (maj/min) sempre aparecem.', ru: 'Если написано, что данных об аппликатуре нет, этот вариант ещё не добавлен. Базовые аккорды (maj/min) показываются всегда.', it: 'Se compare che non ci sono dati di diteggiatura, quella variante non è ancora presente. Gli accordi base (maj/min) ci sono sempre.' },

  // ── 4. 전조 & 저장 ──
  m4s1Label: { ko: '전조 (Transpose)', en: 'Transpose', ja: '移調（Transpose）', zh: '移调（Transpose）', es: 'Transportar', fr: 'Transposition', de: 'Transponieren', pt: 'Transpor', ru: 'Транспозиция', it: 'Trasposizione' },
  m4s1Desc: { ko: '코드 탭의 🎵 전조 버튼으로 옮길 키를 고르면 모든 코드가 함께 이동해요.', en: 'Tap 🎵 Transpose in the Chords tab, choose a key, and every chord moves with it.', ja: 'コードタブの🎵移調ボタンで移す先のキーを選ぶと、全てのコードが一緒に動きます。', zh: '在和弦标签页点 🎵 移调，选择目标调，所有和弦会一起移动。', es: 'Pulsa 🎵 Transportar en la pestaña Acordes, elige una tonalidad y todos los acordes se mueven con ella.', fr: 'Touchez 🎵 Transposer dans l’onglet Accords, choisissez une tonalité : tous les accords suivent.', de: 'Im Akkorde-Tab auf 🎵 Transponieren tippen, Zieltonart wählen — alle Akkorde ziehen mit.', pt: 'Toque em 🎵 Transpor na aba Acordes, escolha um tom e todos os acordes se movem junto.', ru: 'Во вкладке «Аккорды» нажмите 🎵 Транспонировать и выберите тональность — все аккорды сдвинутся.', it: 'Nella scheda Accordi tocca 🎵 Trasporre, scegli una tonalità e tutti gli accordi si spostano.' },
  m4s2Label: { ko: '전조 해제', en: 'Clear transpose', ja: '移調の解除', zh: '取消移调', es: 'Quitar el transporte', fr: 'Annuler la transposition', de: 'Transponierung aufheben', pt: 'Limpar transposição', ru: 'Сброс транспозиции', it: 'Annullare la trasposizione' },
  m4s2Desc: { ko: '원래 키로 돌아가려면 ✕ 전조 해제를 탭하세요.', en: 'Tap ✕ Clear transpose to return to the original key.', ja: '元のキーに戻るには「✕ 移調を解除」をタップ。', zh: '点「✕ 取消移调」即可回到原调。', es: 'Toca ✕ Quitar transporte para volver a la tonalidad original.', fr: 'Touchez ✕ Annuler la transposition pour revenir à la tonalité d’origine.', de: 'Mit ✕ Transponierung aufheben geht es zur Ursprungstonart zurück.', pt: 'Toque em ✕ Limpar transposição para voltar ao tom original.', ru: 'Нажмите ✕ Сбросить транспозицию, чтобы вернуться к исходной тональности.', it: 'Tocca ✕ Annulla trasposizione per tornare alla tonalità originale.' },
  m4s3Label: { ko: '진행 저장 (☆)', en: 'Save a progression (☆)', ja: '進行の保存（☆）', zh: '保存进行（☆）', es: 'Guardar una progresión (☆)', fr: 'Enregistrer une progression (☆)', de: 'Folge speichern (☆)', pt: 'Salvar uma progressão (☆)', ru: 'Сохранить последовательность (☆)', it: 'Salvare una progressione (☆)' },
  m4s3Desc: { ko: '이름을 입력해 저장. 곡 이름이나 장르를 써두면 편리해요.', en: 'Save it with a name — a song title or genre makes it easy to find later.', ja: '名前を付けて保存。曲名やジャンルを書いておくと便利です。', zh: '输入名称保存。写上歌名或风格会更好找。', es: 'Guárdala con un nombre; el título de la canción o el género ayudan a encontrarla.', fr: 'Enregistrez-la avec un nom : titre du morceau ou genre, c’est plus facile à retrouver.', de: 'Unter einem Namen speichern — Songtitel oder Genre helfen beim Wiederfinden.', pt: 'Salve com um nome; o título da música ou o gênero ajudam a achar depois.', ru: 'Сохраните с именем — название песни или жанр помогут найти её потом.', it: 'Salvala con un nome: titolo del brano o genere aiutano a ritrovarla.' },
  m4s4Label: { ko: '불러오기', en: 'Load', ja: '読み込み', zh: '载入', es: 'Cargar', fr: 'Charger', de: 'Laden', pt: 'Carregar', ru: 'Загрузка', it: 'Caricare' },
  m4s4Desc: { ko: '저장 목록에서 탭하면 해당 진행이 즉시 복원됩니다. ✕로 삭제.', en: 'Tap an item in the saved list to restore it instantly. Use ✕ to delete.', ja: '保存リストでタップすると即座に復元。✕で削除。', zh: '在已保存列表里点一下即可立刻恢复。用 ✕ 删除。', es: 'Toca un elemento de la lista guardada para restaurarlo al instante. Usa ✕ para borrar.', fr: 'Touchez un élément de la liste enregistrée pour le restaurer aussitôt. ✕ pour supprimer.', de: 'Einen Eintrag in der Liste antippen stellt ihn sofort wieder her. Mit ✕ löschen.', pt: 'Toque em um item da lista salva para restaurá-lo na hora. Use ✕ para excluir.', ru: 'Нажмите запись в списке — последовательность сразу восстановится. ✕ удаляет.', it: 'Tocca una voce nell’elenco salvato per ripristinarla subito. ✕ per eliminarla.' },
  m4Tip: { ko: '저장·마디 개수 모두 무제한 무료!', en: 'Unlimited saves and unlimited bars — all free.', ja: '保存も小節数も無制限、しかも無料！', zh: '保存与小节数都不限，而且免费！', es: 'Guardados y compases ilimitados, y gratis.', fr: 'Enregistrements et mesures illimités — et gratuits.', de: 'Unbegrenzt speichern, unbegrenzt Takte — kostenlos.', pt: 'Salvamentos e compassos ilimitados, de graça.', ru: 'Неограниченные сохранения и такты — бесплатно.', it: 'Salvataggi e battute illimitati, gratis.' },

  // ── 5. 스케일 탭 ──
  m5s1Label: { ko: '스케일 추천', en: 'Scale suggestions', ja: 'スケールの提案', zh: '音阶推荐', es: 'Escalas sugeridas', fr: 'Gammes suggérées', de: 'Skalenvorschläge', pt: 'Escalas sugeridas', ru: 'Подбор гамм', it: 'Scale consigliate' },
  m5s1Desc: { ko: '진행에 코드가 2개 이상 있으면 잘 맞는 스케일을 자동 추천. 탭하면 바로 적용.', en: 'With two or more chords in your progression it suggests matching scales. Tap one to apply it.', ja: '進行にコードが2つ以上あると合うスケールを自動提案。タップで即適用。', zh: '进行里有两个以上和弦时会自动推荐合适的音阶，点一下即应用。', es: 'Con dos o más acordes sugiere escalas que encajan. Tócala para aplicarla.', fr: 'Dès deux accords, l’app propose des gammes adaptées. Touchez pour appliquer.', de: 'Ab zwei Akkorden schlägt sie passende Skalen vor. Antippen wendet sie an.', pt: 'Com dois ou mais acordes, sugere escalas que combinam. Toque para aplicar.', ru: 'Если в последовательности два и более аккорда, подбираются подходящие гаммы. Нажатие применяет.', it: 'Con due o più accordi propone scale adatte. Tocca per applicarla.' },
  m5s2Label: { ko: '스케일 모드 선택', en: 'Choosing a mode', ja: 'スケールモードの選択', zh: '选择调式', es: 'Elegir el modo', fr: 'Choisir le mode', de: 'Modus wählen', pt: 'Escolher o modo', ru: 'Выбор лада', it: 'Scegliere il modo' },
  m5s2Desc: { ko: 'Ionian(장조), Dorian, Phrygian 등 7가지 모드 + Pentatonic, Blues 지원.', en: 'Seven modes — Ionian (major), Dorian, Phrygian and the rest — plus Pentatonic and Blues.', ja: 'Ionian（長調）、Dorian、Phrygianなど7つのモード＋Pentatonic、Bluesに対応。', zh: '支持 Ionian（大调）、Dorian、Phrygian 等 7 种调式，外加五声与布鲁斯。', es: 'Siete modos —Ionian (mayor), Dorian, Phrygian y los demás— más Pentatónica y Blues.', fr: 'Sept modes — Ionien (majeur), Dorien, Phrygien, etc. — plus Pentatonique et Blues.', de: 'Sieben Modi — Ionisch (Dur), Dorisch, Phrygisch und die übrigen — plus Pentatonik und Blues.', pt: 'Sete modos - Ionian (maior), Dorian, Phrygian e os demais - além de Pentatônica e Blues.', ru: 'Семь ладов — ионийский (мажор), дорийский, фригийский и другие — плюс пентатоника и блюз.', it: 'Sette modi — Ionico (maggiore), Dorico, Frigio e gli altri — più Pentatonica e Blues.' },
  m5s3Label: { ko: '구성음 & 다이어그램', en: 'Notes & diagrams', ja: '構成音とダイアグラム', zh: '组成音与图示', es: 'Notas y diagramas', fr: 'Notes et diagrammes', de: 'Töne & Diagramme', pt: 'Notas e diagramas', ru: 'Ноты и схемы', it: 'Note e diagrammi' },
  m5s3Desc: { ko: '선택 후 기타 지판/피아노 건반으로 스케일 시각화.', en: 'Once chosen, the scale is drawn on the guitar fretboard or the piano keys.', ja: '選択後、ギター指板／ピアノ鍵盤でスケールを可視化。', zh: '选好后，会在吉他指板或钢琴键盘上呈现音阶。', es: 'Al elegirla, la escala se dibuja en el diapasón o en las teclas.', fr: 'Une fois choisie, la gamme s’affiche sur le manche ou sur le clavier.', de: 'Nach der Wahl wird die Skala auf Griffbrett oder Klaviatur gezeichnet.', pt: 'Depois de escolher, a escala aparece no braço do violão ou nas teclas.', ru: 'После выбора гамма рисуется на грифе или на клавишах.', it: 'Una volta scelta, la scala viene disegnata sul manico o sui tasti.' },
  m5s4Label: { ko: '다이아토닉 코드', en: 'Diatonic chords', ja: 'ダイアトニックコード', zh: '调内和弦', es: 'Acordes diatónicos', fr: 'Accords diatoniques', de: 'Leitereigene Akkorde', pt: 'Acordes diatônicos', ru: 'Диатонические аккорды', it: 'Accordi diatonici' },
  m5s4Desc: { ko: '이 스케일에서 나오는 코드 7개 표시. 탭하면 소리 재생, [전체 진행에 추가]로 한번에 추가.', en: 'Shows the 7 chords the scale produces. Tap to hear one, or use [Add all to progression].', ja: 'そのスケールから出る7つのコードを表示。タップで再生、[すべて進行に追加]で一括追加。', zh: '显示该音阶产生的 7 个和弦。点击试听，或用[全部加入进行]一次加入。', es: 'Muestra los 7 acordes que da la escala. Toca para oír uno o usa [Añadir todos a la progresión].', fr: 'Affiche les 7 accords de la gamme. Touchez pour écouter, ou [Tout ajouter à la progression].', de: 'Zeigt die 7 Akkorde der Skala. Antippen zum Hören oder [Alle zur Folge hinzufügen].', pt: 'Mostra os 7 acordes da escala. Toque para ouvir ou use [Adicionar tudo à progressão].', ru: 'Показывает 7 аккордов гаммы. Нажмите, чтобы услышать, или «Добавить все в последовательность».', it: 'Mostra i 7 accordi della scala. Tocca per ascoltarne uno o usa [Aggiungi tutto alla progressione].' },
  m5Tip: { ko: '추천 스케일을 탭하면 키가 자동으로 바뀌어요. 진행이 Am이면 A Aeolian이 높은 점수로 뜰 거예요.', en: 'Tapping a suggested scale switches the key for you. If your progression is in Am, A Aeolian will score high.', ja: '推奨スケールをタップするとキーが自動で変わります。進行がAmならA Aeolianが高スコアで出ます。', zh: '点击推荐音阶会自动切换调。如果进行是 Am，A Aeolian 会得高分。', es: 'Al tocar una escala sugerida cambia la tonalidad. Si tu progresión está en Am, A eólico puntuará alto.', fr: 'Toucher une gamme suggérée change la tonalité. Si votre progression est en Am, A éolien aura un score élevé.', de: 'Ein Tipp auf eine vorgeschlagene Skala wechselt die Tonart. Bei einer Am-Folge punktet A-Äolisch hoch.', pt: 'Tocar em uma escala sugerida troca o tom. Se a progressão está em Am, A eólio terá pontuação alta.', ru: 'Нажатие на предложенную гамму меняет тональность. Для последовательности в Am высоко оценится A эолийский.', it: 'Toccare una scala consigliata cambia la tonalità. Se la progressione è in Am, A eolio avrà un punteggio alto.' },

  // ── 6. 분석 탭 ──
  m6s1Label: { ko: '규칙 기반 분석 (무료)', en: 'Rule-based analysis (free)', ja: 'ルールベース分析（無料）', zh: '规则分析（免费）', es: 'Análisis por reglas (gratis)', fr: 'Analyse par règles (gratuit)', de: 'Regelbasierte Analyse (kostenlos)', pt: 'Análise por regras (grátis)', ru: 'Анализ по правилам (бесплатно)', it: 'Analisi a regole (gratis)' },
  m6s1Desc: { ko: '원본 → 중급(7th) → 대리코드 → 트리톤 대리 4가지 버전을 자동 생성. 인터넷 없이 동작.', en: 'Generates four versions — original, intermediate (7ths), substitutes, tritone subs. Works offline.', ja: '原本 → 中級（7th）→ 代理コード → トライトーン代理の4バージョンを自動生成。オフラインで動作。', zh: '自动生成四个版本：原始 → 中级（七和弦）→ 代理和弦 → 三全音代理。离线也能用。', es: 'Genera cuatro versiones: original, intermedia (séptimas), sustitutos y sustitución de tritono. Funciona sin conexión.', fr: 'Génère quatre versions : originale, intermédiaire (septièmes), substitutions, substitution tritonique. Fonctionne hors ligne.', de: 'Erzeugt vier Versionen: Original, Mittelstufe (Septimen), Ersatzakkorde, Tritonus-Substitution. Läuft offline.', pt: 'Gera quatro versões: original, intermediária (sétimas), substitutos e substituição de trítono. Funciona offline.', ru: 'Создаёт четыре версии: оригинал, средняя (септаккорды), замены, тритоновая замена. Работает офлайн.', it: 'Genera quattro versioni: originale, intermedia (settime), sostituti, sostituzione di tritono. Funziona offline.' },
  m6s2Label: { ko: 'AI 분석 (프리미엄)', en: 'AI analysis (Premium)', ja: 'AI分析（プレミアム）', zh: 'AI 分析（高级版）', es: 'Análisis con IA (Premium)', fr: 'Analyse IA (Premium)', de: 'KI-Analyse (Premium)', pt: 'Análise com IA (Premium)', ru: 'ИИ-анализ (Премиум)', it: 'Analisi IA (Premium)' },
  m6s2Desc: { ko: '장르·레벨에 맞는 코드 추천 + 상세 해설을 AI가 생성. 프리미엄이면 별도 설정 없이 바로 사용해요.', en: 'The AI writes chord suggestions and a detailed explanation for your genre and level. With Premium it just works — nothing to set up.', ja: 'ジャンル・レベルに合ったコード提案と詳しい解説をAIが生成。プレミアムなら設定なしですぐ使えます。', zh: 'AI 会按风格与级别生成和弦推荐与详细解说。有高级版就能直接用，无需设置。', es: 'La IA genera acordes recomendados y una explicación detallada según tu género y nivel. Con Premium funciona sin configurar nada.', fr: 'L’IA propose des accords et une explication détaillée selon votre genre et votre niveau. Avec Premium, rien à configurer.', de: 'Die KI liefert Akkordvorschläge und eine ausführliche Erklärung passend zu Genre und Niveau. Mit Premium ohne Einrichtung nutzbar.', pt: 'A IA gera acordes recomendados e uma explicação detalhada conforme gênero e nível. Com Premium funciona sem configurar nada.', ru: 'ИИ подбирает аккорды и пишет подробное объяснение под ваш жанр и уровень. С Премиумом работает сразу, без настройки.', it: 'L’IA propone accordi e una spiegazione dettagliata in base a genere e livello. Con Premium funziona subito, senza configurare nulla.' },
  m6s3Label: { ko: '사용 방법', en: 'How to use it', ja: '使い方', zh: '使用方法', es: 'Cómo se usa', fr: 'Comment l’utiliser', de: 'So geht’s', pt: 'Como usar', ru: 'Как пользоваться', it: 'Come si usa' },
  m6s3Desc: { ko: '분석 탭에서 코드 진행(예: C Am F G)을 입력하고 ✦ AI 분석을 누르면 끝. API 키 같은 건 입력할 필요 없어요.', en: 'In the Analyze tab, type a progression (e.g. C Am F G) and hit ✦ AI analysis. No API key needed.', ja: '分析タブでコード進行（例: C Am F G）を入力し、✦ AI分析を押すだけ。APIキーの入力は不要です。', zh: '在分析标签页输入和弦进行（例：C Am F G），按 ✦ AI 分析即可。不需要输入 API 密钥。', es: 'En la pestaña Análisis escribe una progresión (p. ej. C Am F G) y pulsa ✦ Análisis con IA. No hace falta ninguna clave de API.', fr: 'Dans l’onglet Analyse, saisissez une progression (ex. : C Am F G) et appuyez sur ✦ Analyse IA. Aucune clé API requise.', de: 'Im Analyse-Tab eine Folge eingeben (z. B. C Am F G) und ✦ KI-Analyse drücken. Kein API-Schlüssel nötig.', pt: 'Na aba Análise, digite uma progressão (ex.: C Am F G) e toque em ✦ Análise com IA. Não precisa de chave de API.', ru: 'Во вкладке «Анализ» введите последовательность (напр. C Am F G) и нажмите ✦ ИИ-анализ. Ключ API не нужен.', it: 'Nella scheda Analisi digita una progressione (es. C Am F G) e tocca ✦ Analisi IA. Nessuna chiave API richiesta.' },
  m6s4Label: { ko: '▶ 버튼', en: '▶ button', ja: '▶ ボタン', zh: '▶ 按钮', es: 'Botón ▶', fr: 'Bouton ▶', de: '▶-Taste', pt: 'Botão ▶', ru: 'Кнопка ▶', it: 'Pulsante ▶' },
  m6s4Desc: { ko: '분석 결과 카드의 재생 버튼으로 해당 코드 진행을 미리 들어볼 수 있어요.', en: 'Each result card has a play button so you can hear that version first.', ja: '分析結果カードの再生ボタンで、その進行を試聴できます。', zh: '每张结果卡片都有播放按钮，可以先听听那个版本。', es: 'Cada tarjeta de resultado tiene un botón de reproducción para escuchar esa versión.', fr: 'Chaque carte de résultat a un bouton de lecture pour écouter cette version.', de: 'Jede Ergebniskarte hat eine Wiedergabetaste, um die Version anzuhören.', pt: 'Cada card de resultado tem um botão de reprodução para ouvir aquela versão.', ru: 'На каждой карточке результата есть кнопка воспроизведения — можно послушать вариант.', it: 'Ogni scheda dei risultati ha un pulsante di riproduzione per ascoltare quella versione.' },
  m6Tip: { ko: 'AI 분석은 프리미엄 기능이에요. 규칙 기반 분석은 누구나 무료로 사용 가능!', en: 'AI analysis is a Premium feature. The rule-based analysis is free for everyone.', ja: 'AI分析はプレミアム機能です。ルールベース分析は誰でも無料で使えます！', zh: 'AI 分析属于高级版功能，规则分析人人免费可用！', es: 'El análisis con IA es una función Premium. El análisis por reglas es gratis para todos.', fr: 'L’analyse IA est une fonction Premium. L’analyse par règles est gratuite pour tous.', de: 'Die KI-Analyse ist Premium. Die regelbasierte Analyse ist für alle kostenlos.', pt: 'A análise com IA é um recurso Premium. A análise por regras é grátis para todos.', ru: 'ИИ-анализ — функция Премиума. Анализ по правилам бесплатен для всех.', it: 'L’analisi IA è una funzione Premium. L’analisi a regole è gratis per tutti.' },

  // ── 7. 실전 활용 (시나리오) ──
  m7aLabel: { ko: '팝 발라드 만들기', en: 'Write a pop ballad', ja: 'ポップバラードを作る', zh: '写一首流行抒情曲', es: 'Componer una balada pop', fr: 'Écrire une ballade pop', de: 'Eine Pop-Ballade schreiben', pt: 'Compor uma balada pop', ru: 'Сочинить поп-балладу', it: 'Scrivere una ballata pop' },
  m7a1: { ko: '키 C 장조 선택 → 탐색 시작', en: 'Pick C major, then start exploring', ja: 'キーCメジャーを選択 → 探索を開始', zh: '选择 C 大调 → 开始探索', es: 'Elige Do mayor y empieza a explorar', fr: 'Choisissez Do majeur, puis lancez l’exploration', de: 'C-Dur wählen, dann Erkundung starten', pt: 'Escolha Dó maior e comece a explorar', ru: 'Выберите до мажор и начните поиск', it: 'Scegli Do maggiore e inizia a esplorare' },
  m7a2: { ko: 'I(C) → VI(Am) → IV(F) → V(G) 탭', en: 'Tap I(C) → VI(Am) → IV(F) → V(G)', ja: 'I(C) → VI(Am) → IV(F) → V(G) をタップ', zh: '依次点 I(C) → VI(Am) → IV(F) → V(G)', es: 'Toca I(C) → VI(Am) → IV(F) → V(G)', fr: 'Touchez I(C) → VI(Am) → IV(F) → V(G)', de: 'I(C) → VI(Am) → IV(F) → V(G) antippen', pt: 'Toque I(C) → VI(Am) → IV(F) → V(G)', ru: 'Нажмите I(C) → VI(Am) → IV(F) → V(G)', it: 'Tocca I(C) → VI(Am) → IV(F) → V(G)' },
  m7a3: { ko: 'GPS 루트로 다음 코드 추천 받기', en: 'Let the GPS route suggest what comes next', ja: 'GPSルートで次のコードの提案を受ける', zh: '用 GPS 路线获取下一个和弦建议', es: 'Deja que la ruta GPS sugiera lo siguiente', fr: 'Laissez l’itinéraire GPS proposer la suite', de: 'Die GPS-Route den nächsten Akkord vorschlagen lassen', pt: 'Deixe a rota GPS sugerir o próximo acorde', ru: 'Пусть GPS-маршрут подскажет следующий аккорд', it: 'Lascia che il percorso GPS proponga il seguito' },
  m7a4: { ko: '분석 탭 → 중급 버전으로 7th 추가', en: 'Analyze tab → use the intermediate version to add 7ths', ja: '分析タブ → 中級バージョンで7thを追加', zh: '分析标签页 → 用中级版本加上七和弦', es: 'Pestaña Análisis → usa la versión intermedia para añadir séptimas', fr: 'Onglet Analyse → version intermédiaire pour ajouter des septièmes', de: 'Analyse-Tab → mit der Mittelstufen-Version Septimen ergänzen', pt: 'Aba Análise → use a versão intermediária para acrescentar sétimas', ru: 'Вкладка «Анализ» → средний вариант добавит септимы', it: 'Scheda Analisi → usa la versione intermedia per aggiungere le settime' },
  m7bLabel: { ko: '커버곡 코드 분석', en: 'Analyze a cover song', ja: 'カバー曲のコード分析', zh: '分析翻唱曲的和弦', es: 'Analizar una versión', fr: 'Analyser une reprise', de: 'Einen Coversong analysieren', pt: 'Analisar um cover', ru: 'Разобрать кавер', it: 'Analizzare una cover' },
  m7b1: { ko: '분석 탭 → 코드 직접 입력 (예: Am F C G)', en: 'Analyze tab → type the chords yourself (e.g. Am F C G)', ja: '分析タブ → コードを直接入力（例: Am F C G）', zh: '分析标签页 → 直接输入和弦（例：Am F C G）', es: 'Pestaña Análisis → escribe los acordes (p. ej. Am F C G)', fr: 'Onglet Analyse → saisissez les accords (ex. : Am F C G)', de: 'Analyse-Tab → Akkorde selbst eingeben (z. B. Am F C G)', pt: 'Aba Análise → digite os acordes (ex.: Am F C G)', ru: 'Вкладка «Анализ» → введите аккорды (напр. Am F C G)', it: 'Scheda Analisi → digita gli accordi (es. Am F C G)' },
  m7b2: { ko: '규칙 기반 분석 실행', en: 'Run the rule-based analysis', ja: 'ルールベース分析を実行', zh: '运行规则分析', es: 'Ejecuta el análisis por reglas', fr: 'Lancez l’analyse par règles', de: 'Regelbasierte Analyse ausführen', pt: 'Rode a análise por regras', ru: 'Запустите анализ по правилам', it: 'Avvia l’analisi a regole' },
  m7b3: { ko: '대리코드 버전으로 편곡 아이디어 얻기', en: 'Take arrangement ideas from the substitute version', ja: '代理コード版から編曲のアイデアを得る', zh: '从代理和弦版本获取编曲灵感', es: 'Saca ideas de arreglo de la versión con sustitutos', fr: 'Tirez des idées d’arrangement de la version avec substitutions', de: 'Aus der Ersatzakkord-Version Arrangement-Ideen ziehen', pt: 'Tire ideias de arranjo da versão com substitutos', ru: 'Возьмите идеи аранжировки из версии с заменами', it: 'Prendi idee di arrangiamento dalla versione con sostituti' },
  m7b4: { ko: '마음에 드는 버전 ▶로 미리 듣기', en: 'Preview the one you like with ▶', ja: '気に入ったバージョンを▶で試聴', zh: '用 ▶ 试听喜欢的版本', es: 'Escucha con ▶ la que más te guste', fr: 'Écoutez celle qui vous plaît avec ▶', de: 'Die Lieblingsversion mit ▶ anhören', pt: 'Ouça com ▶ a que você preferir', ru: 'Послушайте понравившийся вариант через ▶', it: 'Ascolta con ▶ quella che preferisci' },
  m7cLabel: { ko: '스케일로 즉흥 연주', en: 'Improvise with a scale', ja: 'スケールで即興演奏', zh: '用音阶即兴', es: 'Improvisar con una escala', fr: 'Improviser avec une gamme', de: 'Mit einer Skala improvisieren', pt: 'Improvisar com uma escala', ru: 'Импровизация по гамме', it: 'Improvvisare con una scala' },
  m7c1: { ko: '키 A 단조 → 탐색 시작', en: 'A minor, then start exploring', ja: 'キーAマイナー → 探索を開始', zh: '选 A 小调 → 开始探索', es: 'La menor y empieza a explorar', fr: 'La mineur, puis lancez l’exploration', de: 'a-Moll, dann Erkundung starten', pt: 'Lá menor e comece a explorar', ru: 'Ля минор, затем начните поиск', it: 'La minore, poi inizia a esplorare' },
  m7c2: { ko: '코드 탭에서 Am - Dm - E7 추가', en: 'Add Am - Dm - E7 in the Chords tab', ja: 'コードタブで Am - Dm - E7 を追加', zh: '在和弦标签页加入 Am - Dm - E7', es: 'Añade Am - Dm - E7 en la pestaña Acordes', fr: 'Ajoutez Am - Dm - E7 dans l’onglet Accords', de: 'Im Akkorde-Tab Am - Dm - E7 hinzufügen', pt: 'Adicione Am - Dm - E7 na aba Acordes', ru: 'Во вкладке «Аккорды» добавьте Am - Dm - E7', it: 'Aggiungi Am - Dm - E7 nella scheda Accordi' },
  m7c3: { ko: '스케일 탭 → A Aeolian 추천 확인', en: 'Scales tab → check the A Aeolian suggestion', ja: 'スケールタブ → A Aeolianの提案を確認', zh: '音阶标签页 → 查看 A Aeolian 推荐', es: 'Pestaña Escalas → mira la sugerencia A eólico', fr: 'Onglet Gammes → regardez la suggestion La éolien', de: 'Skalen-Tab → Vorschlag A-Äolisch ansehen', pt: 'Aba Escalas → veja a sugestão Lá eólio', ru: 'Вкладка «Гаммы» → посмотрите вариант A эолийский', it: 'Scheda Scale → guarda la proposta La eolio' },
  m7c4: { ko: '기타 지판에서 포지션 확인 후 연주', en: 'Find the position on the fretboard and play', ja: 'ギター指板でポジションを確認して演奏', zh: '在指板上确认把位后开始演奏', es: 'Localiza la posición en el diapasón y toca', fr: 'Repérez la position sur le manche et jouez', de: 'Die Lage auf dem Griffbrett suchen und spielen', pt: 'Ache a posição no braço e toque', ru: 'Найдите позицию на грифе и играйте', it: 'Trova la posizione sul manico e suona' },
};
